### ISSUE TITLE
Alternative for the GTY Wrapper?

### ISSUE THREAD

**Issue by Beauxrel** [ttchisholm/10g-low-latency-ethernet#2]
I do not have a Xilinx UltraScale+, Im sure that's alright... (Im learning) is there an alternative for the ZYBO-Z2 board?

**Comment by ttchisholm** [comment]
I'm not sure if you mean ZYBO Z7 or PYNQ Z2 but both have Z7000 series parts with CLG400 packages so unfortunately don't have any high speed transceivers. ([Zynq 7000 Overview](https://docs.amd.com/v/u/en-US/ds190-Zynq-7000-Overview) Table 2)
